version: "3.8"

services:
  movie-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_API_POSTER_URL=${VITE_API_POSTER_URL}
      - VITE_APP_TITLE=${VITE_APP_TITLE}
      - VITE_APP_DESCRIPTION=${VITE_APP_DESCRIPTION}
    restart: unless-stopped
